### ISSUE TITLE
Github Account suspension 

### ISSUE THREAD

**Issue by telebotengineer** [Oshekher/RDP#1]
Whenever I run workflow, github account gets suspended.
I tried with 5 different account but got same result.

**Comment by Oshekher** [comment]
Well although it should not happen but still try this one : https://github.com/Oshekher/AdityaRDP ( also make account on GitHub after clearing browser data and changing ip address and use gmailnator for temp gmail )

**Comment by telebotengineer** [comment]
It Worked.
thanks a lot :)
